USE [master]
GO

/****** Object:  Database [SSU.ParallelProcessing]    Script Date: 17.03.2024 10:41:02 ******/
CREATE DATABASE [SSU.ParallelProcessing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SSU.ParallelProcessing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SSU.ParallelProcessing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SSU.ParallelProcessing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SSU.ParallelProcessing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SSU.ParallelProcessing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ARITHABORT OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET RECOVERY FULL 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET  MULTI_USER 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SSU.ParallelProcessing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SSU.ParallelProcessing] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SSU.ParallelProcessing] SET QUERY_STORE = ON
GO

ALTER DATABASE [SSU.ParallelProcessing] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SSU.ParallelProcessing] SET  READ_WRITE 
GO


